// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cctiweorsxkxmqdskbrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdGl3ZW9yc3hreG1xZHNrYnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODk3MzgsImV4cCI6MjA3MTM2NTczOH0.IsftolzrxCm53YQbMnzjDly6l5zWz-A6sle-O3fCIjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});